/*
 * ManageMemberReport.java
 *
 * Created on 30 Maret 2008, 16:28
 */
package usu.perpustakaan.buku.widget.operator;

import java.util.Date;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import usu.perpustakaan.buku.widget.admin.ManageOperator;
import usu.perpustakaan.buku.widget.template.TableModelMemberReport;
import usu.perpustakaan.buku.widget.template.TextBoxGlass;
import usu.widget.ButtonGlass;
import usu.widget.util.WidgetUtilities;

/**
 *
 * @author  usu
 */
public class ManageMemberReport extends javax.swing.JPanel {

    private static final long serialVersionUID = -1;
    private TableModelMemberReport model;

    /** Creates new form ManageMemberReport */
    public ManageMemberReport() {
        model = new TableModelMemberReport();
        initComponents();
        table.setModel(model);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(new ManageOperator.RenderTable());
        }
        WidgetUtilities.setAutomaticPopUpMenu(table);

        textSearch.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable(textSearch.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable(textSearch.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable(textSearch.getText());
            }
        });
    }

    /**
     * 
     * @param freez
     */
    public void setFreeze(boolean freez) {
        textSearch.setEnabled(!freez);
        buttonFilter.setEnabled(!freez);
        table.setEnabled(!freez);
        buttonRefresh.setEnabled(!freez);
    }

    public TableModelMemberReport getModel() {
        return model;
    }

    @SuppressWarnings("unchecked")
    public void filterTable(String text) {
        if (text.trim().equals("")) {
            ((TableRowSorter<TableModel>) table.getRowSorter()).setRowFilter(null);
        } else {
            ((TableRowSorter<TableModel>) table.getRowSorter()).setRowFilter(RowFilter.regexFilter(text));
        }
    }

    public ButtonGlass getButtonFilter() {
        return buttonFilter;
    }

    public ButtonGlass getButtonRefresh() {
        return buttonRefresh;
    }

    public JTable getTable() {
        return table;
    }

    public TextBoxGlass getTextSearch() {
        return textSearch;
    }

    /**
     * 
     * @return
     */
    public Date getDaftarUntil() {
        if (!textDaftarSampai.isEnabled()) {
            return null;
        }
        return (Date) textDaftarSampai.getValue();
    }

    /**
     * 
     * @return
     */
    public Date getDaftarFrom() {
        if (!textDaftarDari.isEnabled()) {
            return null;
        }
        return (Date) textDaftarDari.getValue();
    }

    /**
     * 
     * @return
     */
    public Date getLahirUntil() {
        if (!textLahirSampai.isEnabled()) {
            return null;
        }
        return (Date) textLahirSampai.getValue();
    }

    /**
     * 
     * @return
     */
    public Date getLahirFrom() {
        if (!textLahirDari.isEnabled()) {
            return null;
        }
        return (Date) textLahirDari.getValue();
    }

    /**
     * 
     * @return
     */
    public String getNamaAnggota() {
        if (!textName.isEnabled()) {
            return null;
        }
        return textName.getText();
    }

    /**
     * 
     * @return
     */
    public String getIDAnggota() {
        if (!textId.isEnabled()) {
            return null;
        }
        return textId.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usu.perpustakaan.buku.widget.template.ViewPortGlass viewPortGlass1 = new usu.perpustakaan.buku.widget.template.ViewPortGlass();
        table = new javax.swing.JTable();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        textSearch = new usu.perpustakaan.buku.widget.template.TextBoxGlass();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        usu.perpustakaan.buku.widget.template.PanelTranparan panelTranparan1 = new usu.perpustakaan.buku.widget.template.PanelTranparan();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        textId = new usu.perpustakaan.buku.widget.template.TextBoxGlass();
        textName = new usu.perpustakaan.buku.widget.template.TextBoxGlass();
        textLahirDari = new usu.perpustakaan.buku.widget.template.FormatedTextBox();
        textLahirSampai = new usu.perpustakaan.buku.widget.template.FormatedTextBox();
        textDaftarDari = new usu.perpustakaan.buku.widget.template.FormatedTextBox();
        textDaftarSampai = new usu.perpustakaan.buku.widget.template.FormatedTextBox();
        cekId = new javax.swing.JCheckBox();
        ceknama = new javax.swing.JCheckBox();
        ceklahirdari = new javax.swing.JCheckBox();
        ceklahirsampai = new javax.swing.JCheckBox();
        cekdaftardari = new javax.swing.JCheckBox();
        cekdaftarsampai = new javax.swing.JCheckBox();
        buttonRefresh = new usu.widget.ButtonGlass();
        buttonFilter = new usu.widget.ButtonGlass();

        viewPortGlass1.setView(table);

        table.setAutoCreateRowSorter(true);
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setFillsViewportHeight(true);
        table.setOpaque(false);
        table.setSelectionBackground(new java.awt.Color(51, 255, 52));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cari (case sensitive) ");

        textSearch.setForeground(new java.awt.Color(255, 255, 255));
        textSearch.setFont(new java.awt.Font("Tahoma", 1, 11));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewport(viewPortGlass1);

        panelTranparan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTranparan1.setOpaqueImage(false);
        panelTranparan1.setRound(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Id Anggota");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Nama Anggota");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Lahir Dari");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Lahir Sampai");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Terdaftar Dari");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Terdaftar Sampai");

        textId.setForeground(new java.awt.Color(255, 255, 255));
        textId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textId.setFont(new java.awt.Font("Tahoma", 1, 11));

        textName.setForeground(new java.awt.Color(255, 255, 255));
        textName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textName.setFont(new java.awt.Font("Tahoma", 1, 11));

        textLahirDari.setForeground(new java.awt.Color(255, 255, 255));
        textLahirDari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textLahirDari.setFont(new java.awt.Font("Tahoma", 1, 11));
        textLahirDari.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));
        textLahirDari.setValue(new java.util.Date());

        textLahirSampai.setForeground(new java.awt.Color(255, 255, 255));
        textLahirSampai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textLahirSampai.setFont(new java.awt.Font("Tahoma", 1, 11));
        textLahirSampai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));
        textLahirSampai.setValue(new java.util.Date());

        textDaftarDari.setForeground(new java.awt.Color(255, 255, 255));
        textDaftarDari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textDaftarDari.setFont(new java.awt.Font("Tahoma", 1, 11));
        textDaftarDari.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));
        textDaftarDari.setValue(new java.util.Date());

        textDaftarSampai.setForeground(new java.awt.Color(255, 255, 255));
        textDaftarSampai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textDaftarSampai.setFont(new java.awt.Font("Tahoma", 1, 11));
        textDaftarSampai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));
        textDaftarSampai.setValue(new java.util.Date());

        cekId.setSelected(true);
        cekId.setOpaque(false);
        cekId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cekIdItemStateChanged(evt);
            }
        });

        ceknama.setSelected(true);
        ceknama.setOpaque(false);
        ceknama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ceknamaItemStateChanged(evt);
            }
        });

        ceklahirdari.setSelected(true);
        ceklahirdari.setOpaque(false);
        ceklahirdari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ceklahirdariItemStateChanged(evt);
            }
        });

        ceklahirsampai.setSelected(true);
        ceklahirsampai.setOpaque(false);
        ceklahirsampai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ceklahirsampaiItemStateChanged(evt);
            }
        });

        cekdaftardari.setSelected(true);
        cekdaftardari.setOpaque(false);
        cekdaftardari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cekdaftardariItemStateChanged(evt);
            }
        });

        cekdaftarsampai.setSelected(true);
        cekdaftarsampai.setOpaque(false);
        cekdaftarsampai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cekdaftarsampaiItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelTranparan1Layout = new javax.swing.GroupLayout(panelTranparan1);
        panelTranparan1.setLayout(panelTranparan1Layout);
        panelTranparan1Layout.setHorizontalGroup(
            panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranparan1Layout.createSequentialGroup()
                        .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textDaftarDari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addComponent(textLahirSampai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addComponent(textLahirDari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addComponent(textDaftarSampai, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ceknama)
                            .addComponent(ceklahirdari)
                            .addComponent(ceklahirsampai)
                            .addComponent(cekdaftardari)
                            .addComponent(cekdaftarsampai)))
                    .addGroup(panelTranparan1Layout.createSequentialGroup()
                        .addComponent(textId, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cekId)))
                .addContainerGap())
        );
        panelTranparan1Layout.setVerticalGroup(
            panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekId)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceknama)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLahirDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceklahirdari)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLahirSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceklahirsampai)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDaftarDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cekdaftardari)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekdaftarsampai)
                    .addComponent(jLabel7)
                    .addComponent(textDaftarSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonRefresh.setText("Segarkan");
        buttonRefresh.setRoundRect(true);

        buttonFilter.setText("Saring");
        buttonFilter.setRoundRect(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addComponent(panelTranparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                        .addComponent(buttonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTranparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void cekIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cekIdItemStateChanged
    textId.setEnabled(cekId.isSelected());
}//GEN-LAST:event_cekIdItemStateChanged

private void ceknamaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ceknamaItemStateChanged
    textName.setEnabled(ceknama.isSelected());
}//GEN-LAST:event_ceknamaItemStateChanged

private void ceklahirdariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ceklahirdariItemStateChanged
    textLahirDari.setEnabled(ceklahirdari.isSelected());
}//GEN-LAST:event_ceklahirdariItemStateChanged

private void ceklahirsampaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ceklahirsampaiItemStateChanged
    textLahirSampai.setEnabled(ceklahirsampai.isSelected());
}//GEN-LAST:event_ceklahirsampaiItemStateChanged

private void cekdaftardariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cekdaftardariItemStateChanged
    textDaftarDari.setEnabled(cekdaftardari.isSelected());
}//GEN-LAST:event_cekdaftardariItemStateChanged

private void cekdaftarsampaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cekdaftarsampaiItemStateChanged
    textDaftarSampai.setEnabled(cekdaftarsampai.isSelected());
}//GEN-LAST:event_cekdaftarsampaiItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.widget.ButtonGlass buttonFilter;
    usu.widget.ButtonGlass buttonRefresh;
    javax.swing.JCheckBox cekId;
    javax.swing.JCheckBox cekdaftardari;
    javax.swing.JCheckBox cekdaftarsampai;
    javax.swing.JCheckBox ceklahirdari;
    javax.swing.JCheckBox ceklahirsampai;
    javax.swing.JCheckBox ceknama;
    javax.swing.JTable table;
    usu.perpustakaan.buku.widget.template.FormatedTextBox textDaftarDari;
    usu.perpustakaan.buku.widget.template.FormatedTextBox textDaftarSampai;
    usu.perpustakaan.buku.widget.template.TextBoxGlass textId;
    usu.perpustakaan.buku.widget.template.FormatedTextBox textLahirDari;
    usu.perpustakaan.buku.widget.template.FormatedTextBox textLahirSampai;
    usu.perpustakaan.buku.widget.template.TextBoxGlass textName;
    usu.perpustakaan.buku.widget.template.TextBoxGlass textSearch;
    // End of variables declaration//GEN-END:variables
}
