/*
 * PanelActivities.java
 *
 * Created on 26 Maret 2008, 11:32
 */
package usu.perpustakaan.buku.widget.operator;

import usu.perpustakaan.buku.widget.template.ButtonImageReflection;

/**
 *
 * @author  usu
 */
public class PanelActivities extends javax.swing.JPanel {

    private static final long serialVersionUID = -1;

    /** Creates new form PanelActivities */
    public PanelActivities() {
        initComponents();
    }

    public ButtonImageReflection getButtonBorrow() {
        return buttonBorrow;
    }

    public ButtonImageReflection getButtonReturn() {
        return buttonReturn;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBorrow = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();
        buttonReturn = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        buttonBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/Back.png"))); // NOI18N
        buttonBorrow.setMnemonic('p');
        buttonBorrow.setText("Peminjaman Buku");
        buttonBorrow.setToolTipText("Klik untuk masuk ke bagian peminjaman buku");
        add(buttonBorrow, new java.awt.GridBagConstraints());

        buttonReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/Forward.png"))); // NOI18N
        buttonReturn.setMnemonic('B');
        buttonReturn.setText("Pengembalian Buku");
        buttonReturn.setToolTipText("Klik untuk masuk ke bagian pengembalian buku");
        add(buttonReturn, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonBorrow;
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonReturn;
    // End of variables declaration//GEN-END:variables
}
