/*
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2008 echo.khannedy@gmail.com. 
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari echo.khannedy@gmail.com
 * Anda tak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah lisence ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans
 * NoteBook   : Acer Aspire 5920G
 * OS         : Windows Vista
 * Java       : Java 1.6
 * 
 */
package usu.perpustakaan.buku.widget.operator;

import usu.perpustakaan.buku.widget.template.ButtonImageReflection;

/**
 *
 * @author  usu
 */
public class PanelReport extends javax.swing.JPanel {

    private static final long serialVersionUID = -1;

    /** Creates new form PanelReport */
    public PanelReport() {
        initComponents();
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonBook() {
        return buttonBook;
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonBorrow() {
        return buttonBorrow;
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonJoin() {
        return buttonJoin;
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonMember() {
        return buttonMember;
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonReturn() {
        return buttonReturn;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonBorrow = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();
        buttonReturn = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();
        buttonJoin = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();
        buttonBook = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();
        buttonMember = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        buttonBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/Back.png"))); // NOI18N
        buttonBorrow.setMnemonic('P');
        buttonBorrow.setText("Laporan Peminjaman");
        buttonBorrow.setToolTipText("Klik untuk melihat laporan peminjaman");
        add(buttonBorrow, new java.awt.GridBagConstraints());

        buttonReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/Forward.png"))); // NOI18N
        buttonReturn.setMnemonic('E');
        buttonReturn.setText("Laporan Pengembalian");
        buttonReturn.setToolTipText("Klik untuk melihat laporan pengembalian");
        add(buttonReturn, new java.awt.GridBagConstraints());

        buttonJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/addMember.png"))); // NOI18N
        buttonJoin.setMnemonic('A');
        buttonJoin.setText("Laporan Pendaftaran");
        buttonJoin.setToolTipText("Klik untuk melihat laporan pendaftaran anggota");
        add(buttonJoin, new java.awt.GridBagConstraints());

        buttonBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/book.png"))); // NOI18N
        buttonBook.setMnemonic('B');
        buttonBook.setText("Laporan Buku");
        buttonBook.setToolTipText("Klik untuk melihat laporan buku");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(buttonBook, gridBagConstraints);

        buttonMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/user.png"))); // NOI18N
        buttonMember.setMnemonic('O');
        buttonMember.setText("Laporan Anggota");
        buttonMember.setToolTipText("Klik untuk melihat laporan anggota");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(buttonMember, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonBook;
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonBorrow;
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonJoin;
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonMember;
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonReturn;
    // End of variables declaration//GEN-END:variables
}
