/*
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2008 echo.khannedy@gmail.com. 
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari echo.khannedy@gmail.com
 * Anda tak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah lisence ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans
 * NoteBook   : Acer Aspire 5920G
 * OS         : Windows Vista
 * Java       : Java 1.6
 * 
 */
package usu.perpustakaan.buku.widget.admin;

import usu.perpustakaan.buku.widget.template.FormatedTextBox;
import usu.widget.ButtonGlass;
import usu.widget.Panel;

/**
 *
 * @author  usu
 */
public class ManageLibrary extends Panel {

    private static final long serialVersionUID = -1;

    /** Creates new form BeanForm */
    public ManageLibrary() {
        initComponents();
    }

    /**
     * 
     * @return
     */
    public ButtonGlass getButtonReset() {
        return buttonReset;
    }

    /**
     * 
     * @return
     */
    public ButtonGlass getButtonSave() {
        return buttonSave;
    }

    /**
     * 
     * @return
     */
    public FormatedTextBox getTextMaksBorrorBook() {
        return textMaksBorrorBook;
    }

    /**
     * 
     * @return
     */
    public FormatedTextBox getTextMaxBorrowDay() {
        return textMaxBorrowDay;
    }

    /**
     * 
     * @return
     */
    public FormatedTextBox getTextPayforLate() {
        return textPayforLate;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usu.perpustakaan.buku.widget.template.PanelTranparan panelTranparan1 = new usu.perpustakaan.buku.widget.template.PanelTranparan();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        textMaksBorrorBook = new usu.perpustakaan.buku.widget.template.FormatedTextBox();
        textMaxBorrowDay = new usu.perpustakaan.buku.widget.template.FormatedTextBox();
        textPayforLate = new usu.perpustakaan.buku.widget.template.FormatedTextBox();
        buttonSave = new usu.widget.ButtonGlass();
        buttonReset = new usu.widget.ButtonGlass();

        setOpaque(false);
        setOpaqueGradient(false);
        setOpaqueImage(false);

        panelTranparan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelTranparan1.setRound(false);

        jLabel2.setDisplayedMnemonic('B');
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mak Buku Dipinjam");

        jLabel3.setDisplayedMnemonic('H');
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mak Hari Peminjaman");

        jLabel4.setDisplayedMnemonic('D');
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Denda Keterlambatan");

        textMaksBorrorBook.setForeground(new java.awt.Color(255, 255, 255));
        textMaksBorrorBook.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textMaksBorrorBook.setToolTipText("Masukkan maksimal buku yang boleh dipinjam");
        textMaksBorrorBook.setFocusAccelerator('B');
        textMaksBorrorBook.setFont(new java.awt.Font("Tahoma", 1, 11));
        textMaksBorrorBook.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textMaksBorrorBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaksBorrorBookActionPerformed(evt);
            }
        });

        textMaxBorrowDay.setForeground(new java.awt.Color(255, 255, 255));
        textMaxBorrowDay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textMaxBorrowDay.setToolTipText("Masukkan maksimal lama hari peminjaman");
        textMaxBorrowDay.setFocusAccelerator('H');
        textMaxBorrowDay.setFont(new java.awt.Font("Tahoma", 1, 11));
        textMaxBorrowDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textMaxBorrowDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaxBorrowDayActionPerformed(evt);
            }
        });

        textPayforLate.setForeground(new java.awt.Color(255, 255, 255));
        textPayforLate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textPayforLate.setToolTipText("Masukkan denda keterlambatan perhari");
        textPayforLate.setFocusAccelerator('D');
        textPayforLate.setFont(new java.awt.Font("Tahoma", 1, 11));
        textPayforLate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textPayforLate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPayforLateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTranparan1Layout = new javax.swing.GroupLayout(panelTranparan1);
        panelTranparan1.setLayout(panelTranparan1Layout);
        panelTranparan1Layout.setHorizontalGroup(
            panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMaxBorrowDay, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(textMaksBorrorBook, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(textPayforLate, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTranparan1Layout.setVerticalGroup(
            panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textMaksBorrorBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textMaxBorrowDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textPayforLate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonSave.setMnemonic('S');
        buttonSave.setText("Simpan");
        buttonSave.setToolTipText("Klik untuk menyimpan perubahan");
        buttonSave.setRoundRect(true);

        buttonReset.setMnemonic('R');
        buttonReset.setText("Reset");
        buttonReset.setToolTipText("Klik untuk merubah ke pengaturan awal");
        buttonReset.setRoundRect(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTranparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTranparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void textMaksBorrorBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaksBorrorBookActionPerformed
    textMaksBorrorBook.transferFocus();
}//GEN-LAST:event_textMaksBorrorBookActionPerformed

private void textMaxBorrowDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaxBorrowDayActionPerformed
    textMaxBorrowDay.transferFocus();
}//GEN-LAST:event_textMaxBorrowDayActionPerformed

private void textPayforLateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPayforLateActionPerformed
    buttonSave.requestFocusInWindow();
}//GEN-LAST:event_textPayforLateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.widget.ButtonGlass buttonReset;
    usu.widget.ButtonGlass buttonSave;
    usu.perpustakaan.buku.widget.template.FormatedTextBox textMaksBorrorBook;
    usu.perpustakaan.buku.widget.template.FormatedTextBox textMaxBorrowDay;
    usu.perpustakaan.buku.widget.template.FormatedTextBox textPayforLate;
    // End of variables declaration//GEN-END:variables
}
