/*
 * PanelHome.java
 *
 * Created on 29 Maret 2008, 21:18
 */
package usu.perpustakaan.buku.widget.admin;

import usu.perpustakaan.buku.widget.template.ButtonImageReflection;

/**
 *
 * @author  usu
 */
public class PanelHome extends javax.swing.JPanel {

    private static final long serialVersionUID = -1;

    /** Creates new form PanelHome */
    public PanelHome() {
        initComponents();
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonAktivitas() {
        return buttonAktivitas;
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonDatabase() {
        return buttonDatabase;
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonOperator() {
        return buttonOperator;
    }

    /**
     * 
     * @return
     */
    public ButtonImageReflection getButtonPerpustakaan() {
        return buttonPerpustakaan;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPerpustakaan = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();
        buttonDatabase = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();
        buttonOperator = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();
        buttonAktivitas = new usu.perpustakaan.buku.widget.template.ButtonImageReflection();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        buttonPerpustakaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/controlpanel.png"))); // NOI18N
        buttonPerpustakaan.setMnemonic('P');
        buttonPerpustakaan.setText("Perpustakaan");
        buttonPerpustakaan.setToolTipText("Klik untuk masuk ke pengaturan perpustakaan");
        add(buttonPerpustakaan, new java.awt.GridBagConstraints());

        buttonDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/pc.png"))); // NOI18N
        buttonDatabase.setMnemonic('D');
        buttonDatabase.setText("Database");
        buttonDatabase.setToolTipText("Klik untuk masuk ke pengaturan database");
        add(buttonDatabase, new java.awt.GridBagConstraints());

        buttonOperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/operator.png"))); // NOI18N
        buttonOperator.setMnemonic('O');
        buttonOperator.setText("Operator");
        buttonOperator.setToolTipText("Klik untuk melihat data operator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(buttonOperator, gridBagConstraints);

        buttonAktivitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/perpustakaan/buku/resource/Regional Settings.png"))); // NOI18N
        buttonAktivitas.setMnemonic('A');
        buttonAktivitas.setText("Aktivitas Operator");
        buttonAktivitas.setToolTipText("Klik untuk melihat data aktivitas operator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(buttonAktivitas, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonAktivitas;
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonDatabase;
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonOperator;
    usu.perpustakaan.buku.widget.template.ButtonImageReflection buttonPerpustakaan;
    // End of variables declaration//GEN-END:variables
}
